### PR TITLE
add systemd service+timer (SOFTWARE-3234)

### PR DESCRIPTION
**Pull request by edquist**

### CODE REVIEW

**Comment by edquist** [comment]
Does this work?  :)

**Comment by brianhlin** [comment]
That looks pretty good. Have you tried it out on an EL7 VM?

**Comment by edquist** [comment]
No i'll make a scratch build

**Review by matyasselmeci — APPROVED** [review]
LGTM. Feel free to merge once you've tested it.

**Comment by brianhlin** [comment]
@edquist where's the testing on this stand?

**Comment by brianhlin** [comment]
@edquist can we get this across the finish line?

**Comment by brianhlin** [comment]
@sthapa tested this here: https://opensciencegrid.atlassian.net/browse/SOFTWARE-3234

**Pull request merged**
